import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { ThemeProvider, useTheme } from "./contexts/ThemeContext";

function ThemeSwitcher() {
  const { theme, setTheme } = useTheme();
  return (
    <div style={{ position: "fixed", top: 12, right: 16, zIndex: 100 }}>
      <button
        onClick={() => setTheme(theme === "light" ? "dark" : "light")}
        style={{ padding: "0.5em 1em", borderRadius: 6, border: "none", cursor: "pointer" }}
      >
        Switch to {theme === "light" ? "Dark" : "Light"} Mode
      </button>
    </div>
  );
}

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ThemeProvider>
          <ThemeSwitcher />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
