import type { Metadata, Viewport } from 'next';
import './globals.css';
import '../styles/themes/light.css';
import '../styles/themes/dark.css';
import '../styles/tokens.css';
import '../styles/animations.css';
import '../styles/effects.css';
import './styles/theme.css';

import ClientRoot from './ClientRoot';
import GoogleAnalytics from './components/Analytics/GoogleAnalytics';
import { BASE_URL, SITE_NAME } from '../lib/seo';

// Structured data for SEO (JSON-LD)
const jsonLd = {
  '@context': 'https://schema.org',
  '@type': 'WebApplication',
  name: SITE_NAME,
  applicationCategory: 'BusinessApplication',
  operatingSystem: 'Web',
  description: 'AI-powered freelancing platform connecting top talent with global opportunities. Secure blockchain payments, smart matching, and seamless collaboration.',
  url: BASE_URL,
  author: {
    '@type': 'Organization',
    name: SITE_NAME,
    url: BASE_URL,
  },
  offers: {
    '@type': 'Offer',
    price: '0',
    priceCurrency: 'USD',
  },
  aggregateRating: {
    '@type': 'AggregateRating',
    ratingValue: '4.8',
    reviewCount: '2500',
  },
};

const orgJsonLd = {
  '@context': 'https://schema.org',
  '@type': 'Organization',
  name: SITE_NAME,
  url: BASE_URL,
  logo: `${BASE_URL}/icon-512.png`,
  sameAs: [
    'https://www.linkedin.com/company/megilance',
    'https://twitter.com/megilance',
  ],
  contactPoint: [
    {
      '@type': 'ContactPoint',
      contactType: 'customer support',
      email: 'support@megilance.com',
    },
  ],
};

const websiteJsonLd = {
  '@context': 'https://schema.org',
  '@type': 'WebSite',
  url: BASE_URL,
  name: SITE_NAME,
  potentialAction: {
    '@type': 'SearchAction',
    target: `${BASE_URL}/search?q={search_term_string}`,
    'query-input': 'required name=search_term_string',
  },
};

export const metadata: Metadata = {
  metadataBase: new URL(BASE_URL),
  title: {
    default: `${SITE_NAME} - AI-Powered Freelance Marketplace`,
    template: `%s | ${SITE_NAME}`,
  },
  description: 'MegiLance is an AI-powered freelancing platform connecting top talent with global opportunities. Secure blockchain payments, smart matching, and seamless collaboration tools.',
  keywords: [
    'freelance platform',
    'hire freelancers',
    'find clients',
    'remote work',
    'AI matching',
    'blockchain payments',
    'web development',
    'graphic design',
    'content writing',
    'digital marketing',
    'software development',
    'freelance jobs',
    'freelance marketplace',
    'hire developers',
    'MegiLance'
  ],
  manifest: '/manifest.json',
  icons: {
    icon: [
      { url: '/icon.svg', type: 'image/svg+xml' },
      { url: '/icons/icon-192x192.svg', sizes: '192x192', type: 'image/svg+xml' },
      { url: '/icons/icon-512x512.svg', sizes: '512x512', type: 'image/svg+xml' },
    ],
    shortcut: '/icon.svg',
    apple: [
      { url: '/icons/icon-192x192.svg', sizes: '180x180', type: 'image/svg+xml' },
    ],
  },
  authors: [{ name: 'MegiLance Team', url: 'https://megilance.com' }],
  creator: 'MegiLance',
  publisher: 'MegiLance',
  applicationName: 'MegiLance',
  category: 'Business',
  classification: 'Freelance Marketplace',
  
  openGraph: {
    type: 'website',
    locale: 'en_US',
    url: BASE_URL,
    siteName: SITE_NAME,
    title: `${SITE_NAME} - AI-Powered Freelance Platform`,
    description: 'Connect with world-class freelancers and clients. AI-powered matching, secure blockchain payments, real-time collaboration.',
    // Images auto-generated by app/opengraph-image.tsx (Next.js file convention)
  },
  
  twitter: {
    card: 'summary_large_image',
    site: '@megilance',
    creator: '@megilance',
    title: `${SITE_NAME} - AI-Powered Freelance Platform`,
    description: 'Connect with world-class freelancers and clients. AI-powered matching, secure blockchain payments.',
    // Images auto-generated by app/twitter-image.tsx (Next.js file convention)
  },
  
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  
  verification: {
    google: process.env.GOOGLE_SITE_VERIFICATION,
    yandex: process.env.YANDEX_VERIFICATION,
  },
  
  alternates: {
    canonical: BASE_URL,
    languages: {
      'en-US': BASE_URL,
    },
  },
  
  other: {
    'msapplication-TileColor': '#4573df',
    'apple-mobile-web-app-capable': 'yes',
    'apple-mobile-web-app-status-bar-style': 'black-translucent',
    'format-detection': 'telephone=no',
  },
};

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 5,
  userScalable: true,
  themeColor: [
    { media: '(prefers-color-scheme: light)', color: '#ffffff' },
    { media: '(prefers-color-scheme: dark)', color: '#0b0f19' },
  ],
  colorScheme: 'light dark',
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        {/* Google Analytics - FREE forever */}
        <GoogleAnalytics />
        
        {/* Preconnect to important third-party origins */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        
        {/* DNS prefetch for API */}
        <link rel="dns-prefetch" href="//api.stripe.com" />
        
        {/* Structured Data for SEO */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(orgJsonLd) }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(websiteJsonLd) }}
        />
        
        {/* Theme initialization - prevent flash */}
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                try {
                  var theme = localStorage.getItem('megilance-theme');
                  if (!theme) {
                    theme = window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light';
                  }
                  document.documentElement.classList.add(theme);
                  document.documentElement.style.colorScheme = theme;
                } catch (e) {}
              })();
            `,
          }}
        />
      </head>
      <body className="bg-[var(--background)] text-[var(--text-primary)] antialiased">
        <ClientRoot>
          {children}
        </ClientRoot>
      </body>
    </html>
  );
}

